init:
  - git config --global core.autocrlf true
  - nuget sources update -Name nuget.org -Source https://api.nuget.org/v3/index.json
  - nuget sources Add -Name aspnetmaster -Source https://www.myget.org/f/aspnetmaster/api/v3/index.json
  - nuget sources Add -Name myget -Source https://dotnet.myget.org/F/aspnetcore-tools/api/v3/index.json
  - nuget sources Add -Name aspnetci -Source https://www.myget.org/F/aspnetcidev/api/v3/index.json
build_script:
  - build.cmd verify
clone_depth: 1
test: off
deploy: off
